[tool.poetry]
name = "docs.cachix.org"
version = "0.1.0"
description = ""
authors = ["Domen Kožar <domen@cachix.org>"]
license = "CC BY-SA"

[tool.poetry.dependencies]
python = "^3.7"
sphinx = "4.3.2"
livereload = "2.6.3"
sphinx-book-theme = "1.0.1"
sphinx-copybutton = "0.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
