name: "CI"
on: 
- pull_request
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v22
    - name: Build
      run: nix-build
    - name: Link check
      run: nix-shell --run "make linkcheck"

